image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
    - burkeholland.simple-react-snippets@1.2.2:aB/gV0ExPn8v6vEZNUjoWA==
tasks:
  - init: npm install
    command: npm start
ports:
  - port: 3000
    onOpen: open-preview
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: true
    addLabel: prebuilt